<?php 
	// Enqueue Styles and Scripts
	function spark_base_enqueue() {
		wp_enqueue_style( 'spark_fontawesome_css', get_template_directory_uri()."/style/fontawesome/css/fontawesome-all.min.css" );
		wp_enqueue_style( 'spark_base_css', get_stylesheet_directory_uri()."/style.css" );
		
		wp_enqueue_script( 'jquery', $in_footer = true );
		wp_enqueue_script( 'spark_base_js', get_stylesheet_directory_uri()."/js/app.js", $in_footer = true );
	}

	add_action( 'wp_enqueue_scripts', 'spark_base_enqueue' );


	// Our custom post type function
	function create_posttype() {
	 
	    register_post_type( 'jobs',
	    // CPT Options
	        array(
	            'labels' => array(
	                'name' => __( 'Jobs' ),
	                'singular_name' => __( 'Position' )
	            ),
	            'public' => true,
	            'has_archive' => true,
	            'rewrite' => array('slug' => 'jobs'),
	        )
	    );
	}
	// Hooking up our function to theme setup
	add_action( 'init', 'create_posttype' );


	//Newsletter Widget
	if ( function_exists('register_sidebar') ) {
		register_sidebar(array(
			'name' => 'Newsletter Form',
			'id' => 'newsletter-form',
			'description' => 'Sendgrid form widget',
			'before_widget' => '<div id="%1$s" class="widget %2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h2 class="widgettitle">',
			'after_title' => '</h2>',
		));
	}


	// if(function_exists("register_field_group"))
	// {
	// 	register_field_group(array (
	// 		'id' => 'acf_content',
	// 		'title' => 'Content',
	// 		'fields' => array (
	// 			array (
	// 				'key' => 'field_5bbb54572a7b9',
	// 				'label' => 'Template',
	// 				'name' => 'template',
	// 				'type' => 'select',
	// 				'choices' => array (
	// 					'default' => 'Content Page',
	// 				),
	// 				'default_value' => '',
	// 				'allow_null' => 1,
	// 				'multiple' => 0,
	// 			),
	// 			array (
	// 				'key' => 'field_5a9b21f9f75e1',
	// 				'label' => 'Layout',
	// 				'name' => 'layout',
	// 				'type' => 'flexible_content',
	// 				'layouts' => array (
	// 					array (
	// 						'label' => 'Hero',
	// 						'name' => 'hero',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5a9f9312fc457',
	// 								'label' => 'Background Image',
	// 								'name' => 'background_image',
	// 								'type' => 'image',
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 							array (
	// 								'key' => 'field_5a9f9328fc458',
	// 								'label' => 'Background Color',
	// 								'name' => 'background_color',
	// 								'type' => 'color_picker',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5a9f933afc459',
	// 								'label' => 'Content Position',
	// 								'name' => 'content_position',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'left' => 'Left',
	// 									'center' => 'Center',
	// 									'right' => 'Right',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 1,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5a9f938dfc45a',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'no',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Video Hero',
	// 						'name' => 'vimeo_hero',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5aa9fd9a0504b',
	// 								'label' => 'YouTube ID',
	// 								'name' => 'youtube_id',
	// 								'type' => 'text',
	// 								'instructions' => 'Please include only the 9 digit code at the end of the video url ( ie. 260073683 )',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bb9053ea4854',
	// 								'label' => 'Placeholder Image',
	// 								'name' => 'placeholder_img',
	// 								'type' => 'image',
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 							array (
	// 								'key' => 'field_5aa9fe950504c',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 							array (
	// 								'key' => 'field_5aa9fea70504d',
	// 								'label' => 'Content Position',
	// 								'name' => 'content_position',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'left' => 'Left',
	// 									'center' => 'Center',
	// 									'right' => 'Right',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 0,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5c1907dbf23e3',
	// 								'label' => 'Video Url',
	// 								'name' => 'video_url',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Content Block',
	// 						'name' => 'content_block',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bf58db04e042',
	// 								'label' => 'Section ID',
	// 								'name' => 'section_id',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5aa8955536be8',
	// 								'label' => 'Background Color',
	// 								'name' => 'background_color',
	// 								'type' => 'color_picker',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5aa8955536be9',
	// 								'label' => 'Content Position',
	// 								'name' => 'content_position',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'left' => 'Left',
	// 									'center' => 'Center',
	// 									'right' => 'Right',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 1,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5aa8955536bea',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'no',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Section Heading',
	// 						'name' => 'section_heading',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5ab2faead21e7',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Content Card',
	// 						'name' => 'content_card',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5ab2847311eed',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'no',
	// 							),
	// 							array (
	// 								'key' => 'field_5ab2848511eee',
	// 								'label' => 'Heading',
	// 								'name' => '',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5ab284988139f',
	// 								'label' => 'Background Image',
	// 								'name' => 'background_image',
	// 								'type' => 'image',
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 							array (
	// 								'key' => 'field_5ab284ae813a0',
	// 								'label' => 'Image',
	// 								'name' => 'image',
	// 								'type' => 'image',
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Tabs',
	// 						'name' => 'tabs',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5b0b082de26b2',
	// 								'label' => 'Template',
	// 								'name' => 'template',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'horizontal_stack' => 'horizontal stack',
	// 									'tabs' => 'tabs',
	// 									'vertical_stack' => 'vertical stack',
	// 								),
	// 								'default_value' => 'horizontal_stack',
	// 								'allow_null' => 0,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5a9b2212f75e2',
	// 								'label' => 'Tab Items',
	// 								'name' => 'tab_items',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5a9b2239f75e3',
	// 										'label' => 'Heading',
	// 										'name' => 'heading',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa37056e9dd5',
	// 										'label' => 'Tab image',
	// 										'name' => 'tab_image',
	// 										'type' => 'image',
	// 										'column_width' => '',
	// 										'save_format' => 'object',
	// 										'preview_size' => 'thumbnail',
	// 										'library' => 'all',
	// 									),
	// 									array (
	// 										'key' => 'field_5a9b2249f75e4',
	// 										'label' => 'Content',
	// 										'name' => 'content',
	// 										'type' => 'wysiwyg',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'toolbar' => 'full',
	// 										'media_upload' => 'yes',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'row',
	// 								'button_label' => 'Add Tab',
	// 							),
	// 							array (
	// 								'key' => 'field_5c00954224066',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'FAQ Accordion',
	// 						'name' => 'faq_accordion',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5aa8ca3224a71',
	// 								'label' => 'Accordion Group',
	// 								'name' => 'accordion_group',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5aa8ca3224a72',
	// 										'label' => 'Heading',
	// 										'name' => 'heading',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa8ca6b24a75',
	// 										'label' => 'Accordion',
	// 										'name' => 'accordion',
	// 										'type' => 'repeater',
	// 										'column_width' => '',
	// 										'sub_fields' => array (
	// 											array (
	// 												'key' => 'field_5aa8ca9d24a76',
	// 												'label' => 'Heading',
	// 												'name' => 'heading',
	// 												'type' => 'text',
	// 												'column_width' => '',
	// 												'default_value' => '',
	// 												'placeholder' => '',
	// 												'prepend' => '',
	// 												'append' => '',
	// 												'formatting' => 'html',
	// 												'maxlength' => '',
	// 											),
	// 											array (
	// 												'key' => 'field_5aa8caa524a77',
	// 												'label' => 'Content',
	// 												'name' => 'content',
	// 												'type' => 'wysiwyg',
	// 												'column_width' => '',
	// 												'default_value' => '',
	// 												'toolbar' => 'basic',
	// 												'media_upload' => 'yes',
	// 											),
	// 										),
	// 										'row_min' => '',
	// 										'row_limit' => '',
	// 										'layout' => 'row',
	// 										'button_label' => 'Add Row',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'row',
	// 								'button_label' => 'Add Tab',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Content With Image',
	// 						'name' => 'content_with_image',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5a9b2856585df',
	// 								'label' => 'Image',
	// 								'name' => 'image',
	// 								'type' => 'image',
	// 								'conditional_logic' => array (
	// 									'status' => 1,
	// 									'rules' => array (
	// 										array (
	// 											'field' => 'field_5bdfbd83e9a65',
	// 											'operator' => '!=',
	// 											'value' => 'staggered',
	// 										),
	// 									),
	// 									'allorany' => 'all',
	// 								),
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 							array (
	// 								'key' => 'field_5bea08ed41311',
	// 								'label' => 'Gallery',
	// 								'name' => 'gallery',
	// 								'type' => 'repeater',
	// 								'conditional_logic' => array (
	// 									'status' => 1,
	// 									'rules' => array (
	// 										array (
	// 											'field' => 'field_5bdfbd83e9a65',
	// 											'operator' => '==',
	// 											'value' => 'staggered',
	// 										),
	// 									),
	// 									'allorany' => 'all',
	// 								),
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5bea08fd41312',
	// 										'label' => 'Image',
	// 										'name' => 'image',
	// 										'type' => 'image',
	// 										'column_width' => '',
	// 										'save_format' => 'object',
	// 										'preview_size' => 'thumbnail',
	// 										'library' => 'all',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 							array (
	// 								'key' => 'field_5a9b2865585e0',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 							array (
	// 								'key' => 'field_5bbadf5a97433',
	// 								'label' => 'Content Position',
	// 								'name' => 'content_position',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'left' => 'Left',
	// 									'right' => 'Right',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 0,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5bdfbd83e9a65',
	// 								'label' => 'Template',
	// 								'name' => 'template',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'default' => 'Default',
	// 									'staggered' => 'Staggered',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 0,
	// 								'multiple' => 0,
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Icon Grid',
	// 						'name' => 'icon_grid',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5aa2d23b8a578',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5b4f417c7d255',
	// 								'label' => 'Heading Size',
	// 								'name' => 'heading_size',
	// 								'type' => 'select',
	// 								'column_width' => '',
	// 								'choices' => array (
	// 									'small' => 'small',
	// 									'large' => 'large',
	// 								),
	// 								'default_value' => '',
	// 								'allow_null' => 0,
	// 								'multiple' => 0,
	// 							),
	// 							array (
	// 								'key' => 'field_5aa2d2488a579',
	// 								'label' => 'Collection',
	// 								'name' => 'collection',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5aa2d2548a57a',
	// 										'label' => 'image',
	// 										'name' => 'image',
	// 										'type' => 'image',
	// 										'column_width' => '',
	// 										'save_format' => 'object',
	// 										'preview_size' => 'thumbnail',
	// 										'library' => 'all',
	// 									),
	// 									array (
	// 										'key' => 'field_5b43a07916666',
	// 										'label' => 'link',
	// 										'name' => 'link',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Team Grid',
	// 						'name' => 'team_grid',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5aa891148332d',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5aa891148332e',
	// 								'label' => 'Collection',
	// 								'name' => 'collection',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5aa891148332f',
	// 										'label' => 'Profile Image',
	// 										'name' => 'image',
	// 										'type' => 'image',
	// 										'column_width' => '',
	// 										'save_format' => 'object',
	// 										'preview_size' => 'thumbnail',
	// 										'library' => 'all',
	// 									),
	// 									array (
	// 										'key' => 'field_5c17e1f275a06',
	// 										'label' => 'Profile Image-Hover',
	// 										'name' => 'profile_image_hover',
	// 										'type' => 'image',
	// 										'column_width' => '',
	// 										'save_format' => 'object',
	// 										'preview_size' => 'thumbnail',
	// 										'library' => 'all',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa8915e83330',
	// 										'label' => 'Name',
	// 										'name' => 'name',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa8916883331',
	// 										'label' => 'Title',
	// 										'name' => 'title',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa8917583332',
	// 										'label' => 'Institution',
	// 										'name' => 'institution',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5aa8bef0cde89',
	// 										'label' => 'Content',
	// 										'name' => 'profile_content',
	// 										'type' => 'wysiwyg',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'toolbar' => 'full',
	// 										'media_upload' => 'no',
	// 									),
	// 									array (
	// 										'key' => 'field_5bd2b551bf3ec',
	// 										'label' => 'Social Icons',
	// 										'name' => 'social_icons',
	// 										'type' => 'repeater',
	// 										'column_width' => '',
	// 										'sub_fields' => array (
	// 											array (
	// 												'key' => 'field_5bd2b56bbf3ed',
	// 												'label' => 'Social Site Name',
	// 												'name' => 'social_site_name',
	// 												'type' => 'text',
	// 												'column_width' => '',
	// 												'default_value' => '',
	// 												'placeholder' => '',
	// 												'prepend' => '',
	// 												'append' => '',
	// 												'formatting' => 'html',
	// 												'maxlength' => '',
	// 											),
	// 											array (
	// 												'key' => 'field_5bd2b578bf3ee',
	// 												'label' => 'Social Site Url',
	// 												'name' => 'social_site_url',
	// 												'type' => 'text',
	// 												'column_width' => '',
	// 												'default_value' => '',
	// 												'placeholder' => '',
	// 												'prepend' => '',
	// 												'append' => '',
	// 												'formatting' => 'html',
	// 												'maxlength' => '',
	// 											),
	// 										),
	// 										'row_min' => '',
	// 										'row_limit' => '',
	// 										'layout' => 'table',
	// 										'button_label' => 'Add Row',
	// 									),
	// 									array (
	// 										'key' => 'field_5c17e43dfd3be',
	// 										'label' => 'Developer?',
	// 										'name' => 'developer',
	// 										'type' => 'true_false',
	// 										'column_width' => '',
	// 										'message' => '',
	// 										'default_value' => 0,
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'row',
	// 								'button_label' => 'Add Member',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Statistics',
	// 						'name' => 'statistics',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bbabc5784171',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bbabc5c84172',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 							array (
	// 								'key' => 'field_5bbabc6684173',
	// 								'label' => 'Statistics',
	// 								'name' => 'statistics',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5bbabc7384174',
	// 										'label' => 'Statistic',
	// 										'name' => 'statistic',
	// 										'type' => 'select',
	// 										'column_width' => '',
	// 										'choices' => array (
	// 											'backlogged-transactions' => '# of Backlogged Transactions',
	// 											'average-transaction-cost' => 'Average Transaction Cost',
	// 											'uncle-blocks' => '# of Uncle Blocks',
	// 										),
	// 										'default_value' => '',
	// 										'allow_null' => 0,
	// 										'multiple' => 0,
	// 									),
	// 									array (
	// 										'key' => 'field_5bbabcdb8f7ed',
	// 										'label' => 'Subheading',
	// 										'name' => 'subheading',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5bbabce38f7ee',
	// 										'label' => 'Text',
	// 										'name' => 'text',
	// 										'type' => 'textarea',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'maxlength' => '',
	// 										'rows' => '',
	// 										'formatting' => 'br',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Iframe',
	// 						'name' => 'iframe',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bd1e51af3799',
	// 								'label' => 'Url',
	// 								'name' => 'url',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bd1e51ef379a',
	// 								'label' => 'Height',
	// 								'name' => 'height',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Positions',
	// 						'name' => 'positions',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5be0580aa049c',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bdfae1f567f0',
	// 								'label' => 'Posts',
	// 								'name' => 'posts',
	// 								'type' => 'relationship',
	// 								'column_width' => '',
	// 								'return_format' => 'object',
	// 								'post_type' => array (
	// 									0 => 'jobs',
	// 								),
	// 								'taxonomy' => array (
	// 									0 => 'all',
	// 								),
	// 								'filters' => array (
	// 									0 => 'search',
	// 								),
	// 								'result_elements' => array (
	// 									0 => 'post_type',
	// 									1 => 'post_title',
	// 								),
	// 								'max' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bf4d72eec82b',
	// 								'label' => 'See More Text',
	// 								'name' => 'see_more_text',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bf4d756ec82c',
	// 								'label' => 'See More Link',
	// 								'name' => 'see_more_link',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Link List',
	// 						'name' => 'link_list',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5be0591156e17',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5be0591156e18',
	// 								'label' => 'Posts',
	// 								'name' => 'posts',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5be0593756e19',
	// 										'label' => 'Title',
	// 										'name' => 'title',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5be0594a56e1a',
	// 										'label' => 'Date',
	// 										'name' => 'date',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5be0595356e1b',
	// 										'label' => 'Link Url',
	// 										'name' => 'link',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 							array (
	// 								'key' => 'field_5bea0d05e3e96',
	// 								'label' => 'See More Text',
	// 								'name' => 'see_more_text',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bea0d0fe3e97',
	// 								'label' => 'See More Link',
	// 								'name' => 'see_more_link',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Video Feed',
	// 						'name' => 'video_list',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5be05c5d32a85',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5be05c6632a86',
	// 								'label' => 'Videos',
	// 								'name' => 'videos',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5be05c7632a87',
	// 										'label' => 'Youtube ID',
	// 										'name' => 'youtube_id',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5be05c8732a88',
	// 										'label' => 'Title',
	// 										'name' => 'title',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5be05c8f32a89',
	// 										'label' => 'Description',
	// 										'name' => 'description',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 							array (
	// 								'key' => 'field_5bfb1ba1d6767',
	// 								'label' => 'See More Text',
	// 								'name' => 'see_more_text',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bfb1badd6768',
	// 								'label' => 'See More Link',
	// 								'name' => 'see_more_link',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 				),
	// 				'button_label' => 'Add Row',
	// 				'min' => '',
	// 				'max' => '',
	// 			),
	// 		),
	// 		'location' => array (
	// 			array (
	// 				array (
	// 					'param' => 'post_type',
	// 					'operator' => '==',
	// 					'value' => 'post',
	// 					'order_no' => 0,
	// 					'group_no' => 0,
	// 				),
	// 			),
	// 			array (
	// 				array (
	// 					'param' => 'post_type',
	// 					'operator' => '==',
	// 					'value' => 'page',
	// 					'order_no' => 0,
	// 					'group_no' => 1,
	// 				),
	// 			),
	// 		),
	// 		'options' => array (
	// 			'position' => 'normal',
	// 			'layout' => 'no_box',
	// 			'hide_on_screen' => array (
	// 			),
	// 		),
	// 		'menu_order' => 0,
	// 	));
	// 	register_field_group(array (
	// 		'id' => 'acf_poc',
	// 		'title' => 'POC',
	// 		'fields' => array (
	// 			array (
	// 				'key' => 'field_5bff0720c07a9',
	// 				'label' => 'POC Tabs',
	// 				'name' => 'poc_tabs',
	// 				'type' => 'flexible_content',
	// 				'layouts' => array (
	// 					array (
	// 						'label' => 'POC',
	// 						'name' => 'poc',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bff09b5c07ab',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bff09adc07aa',
	// 								'label' => 'Iframe Url',
	// 								'name' => 'iframe_url',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bff1c7c2c6a3',
	// 								'label' => 'Iframe Height',
	// 								'name' => 'iframe_height',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'FAQ',
	// 						'name' => 'faq',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bff0b55c07b0',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5bff0b1cc07ad',
	// 								'label' => 'List',
	// 								'name' => 'list',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5bff0b38c07ae',
	// 										'label' => 'Heading',
	// 										'name' => 'heading',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5bff0b3dc07af',
	// 										'label' => 'Content',
	// 										'name' => 'content',
	// 										'type' => 'wysiwyg',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'toolbar' => 'full',
	// 										'media_upload' => 'yes',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => 3,
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Tab',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Topology',
	// 						'name' => 'topology',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5bff0dafef999',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 							array (
	// 								'key' => 'field_5bff0de2ef99a',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 				),
	// 				'button_label' => 'Add Row',
	// 				'min' => '',
	// 				'max' => '',
	// 			),
	// 		),
	// 		'location' => array (
	// 			array (
	// 				array (
	// 					'param' => 'page',
	// 					'operator' => '==',
	// 					'value' => '314',
	// 					'order_no' => 0,
	// 					'group_no' => 0,
	// 				),
	// 			),
	// 		),
	// 		'options' => array (
	// 			'position' => 'normal',
	// 			'layout' => 'no_box',
	// 			'hide_on_screen' => array (
	// 			),
	// 		),
	// 		'menu_order' => 0,
	// 	));
	// 	register_field_group(array (
	// 		'id' => 'acf_position',
	// 		'title' => 'Position',
	// 		'fields' => array (
	// 			array (
	// 				'key' => 'field_5b0b35c7bf574',
	// 				'label' => 'Image',
	// 				'name' => 'image',
	// 				'type' => 'image',
	// 				'save_format' => 'object',
	// 				'preview_size' => 'thumbnail',
	// 				'library' => 'all',
	// 			),
	// 			array (
	// 				'key' => 'field_5b0b359bbf572',
	// 				'label' => 'Location',
	// 				'name' => 'location',
	// 				'type' => 'text',
	// 				'default_value' => '',
	// 				'placeholder' => '',
	// 				'prepend' => '',
	// 				'append' => '',
	// 				'formatting' => 'html',
	// 				'maxlength' => '',
	// 			),
	// 			array (
	// 				'key' => 'field_5b0b35b9bf573',
	// 				'label' => 'Position Type',
	// 				'name' => 'position_type',
	// 				'type' => 'text',
	// 				'default_value' => '',
	// 				'placeholder' => '',
	// 				'prepend' => '',
	// 				'append' => '',
	// 				'formatting' => 'html',
	// 				'maxlength' => '',
	// 			),
	// 			array (
	// 				'key' => 'field_5b0b3608a3b1f',
	// 				'label' => 'Job Description',
	// 				'name' => 'job_description',
	// 				'type' => 'wysiwyg',
	// 				'default_value' => '',
	// 				'toolbar' => 'full',
	// 				'media_upload' => 'yes',
	// 			),
	// 			array (
	// 				'key' => 'field_5c06b83f7403c',
	// 				'label' => 'Apply Link',
	// 				'name' => 'apply_url',
	// 				'type' => 'text',
	// 				'default_value' => '',
	// 				'placeholder' => '',
	// 				'prepend' => '',
	// 				'append' => '',
	// 				'formatting' => 'html',
	// 				'maxlength' => '',
	// 			),
	// 		),
	// 		'location' => array (
	// 			array (
	// 				array (
	// 					'param' => 'post_type',
	// 					'operator' => '==',
	// 					'value' => 'jobs',
	// 					'order_no' => 0,
	// 					'group_no' => 0,
	// 				),
	// 			),
	// 		),
	// 		'options' => array (
	// 			'position' => 'normal',
	// 			'layout' => 'no_box',
	// 			'hide_on_screen' => array (
	// 				0 => 'the_content',
	// 			),
	// 		),
	// 		'menu_order' => 0,
	// 	));
	// 	register_field_group(array (
	// 		'id' => 'acf_resources',
	// 		'title' => 'Resources',
	// 		'fields' => array (
	// 			array (
	// 				'key' => 'field_5c143f0936175',
	// 				'label' => 'Resource Sidebar',
	// 				'name' => 'resource_sidebar',
	// 				'type' => 'flexible_content',
	// 				'layouts' => array (
	// 					array (
	// 						'label' => 'Link List',
	// 						'name' => 'link_list',
	// 						'display' => 'row',
	// 						'min' => 1,
	// 						'max' => 1,
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5c143fa036176',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5c143fb236177',
	// 								'label' => 'Posts',
	// 								'name' => 'posts',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5c143fc636178',
	// 										'label' => 'Title',
	// 										'name' => 'title',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5c143fd236179',
	// 										'label' => 'Date',
	// 										'name' => 'date',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5c143fe03617a',
	// 										'label' => 'Link Url',
	// 										'name' => 'link',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'row',
	// 								'button_label' => 'Add Row',
	// 							),
	// 							array (
	// 								'key' => 'field_5c14402e3617b',
	// 								'label' => 'See More Text',
	// 								'name' => 'see_more_text',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5c14403c3617c',
	// 								'label' => 'See More Link',
	// 								'name' => 'see_more_link',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 					array (
	// 						'label' => 'Whitepaper Callout',
	// 						'name' => 'whitepaper',
	// 						'display' => 'row',
	// 						'min' => '',
	// 						'max' => '',
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5c151b10da0fb',
	// 								'label' => 'Image',
	// 								'name' => 'image',
	// 								'type' => 'image',
	// 								'column_width' => '',
	// 								'save_format' => 'object',
	// 								'preview_size' => 'thumbnail',
	// 								'library' => 'all',
	// 							),
	// 							array (
	// 								'key' => 'field_5c1440623617e',
	// 								'label' => 'Content',
	// 								'name' => 'content',
	// 								'type' => 'wysiwyg',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'toolbar' => 'full',
	// 								'media_upload' => 'yes',
	// 							),
	// 						),
	// 					),
	// 				),
	// 				'button_label' => 'Add Row',
	// 				'min' => 1,
	// 				'max' => '',
	// 			),
	// 			array (
	// 				'key' => 'field_5c150a77ef140',
	// 				'label' => 'Resource	Videos',
	// 				'name' => 'resource_videos',
	// 				'type' => 'flexible_content',
	// 				'layouts' => array (
	// 					array (
	// 						'label' => 'Video Feed',
	// 						'name' => 'video_list',
	// 						'display' => 'row',
	// 						'min' => 1,
	// 						'max' => 1,
	// 						'sub_fields' => array (
	// 							array (
	// 								'key' => 'field_5c150b1eef141',
	// 								'label' => 'Heading',
	// 								'name' => 'heading',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5c150b2aef142',
	// 								'label' => 'Videos',
	// 								'name' => 'videos',
	// 								'type' => 'repeater',
	// 								'column_width' => '',
	// 								'sub_fields' => array (
	// 									array (
	// 										'key' => 'field_5c150b3cef143',
	// 										'label' => 'Youtube ID',
	// 										'name' => 'youtube_id',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5c150b50ef144',
	// 										'label' => 'Title',
	// 										'name' => 'title',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 									array (
	// 										'key' => 'field_5c150b57ef145',
	// 										'label' => 'Description',
	// 										'name' => 'description',
	// 										'type' => 'text',
	// 										'column_width' => '',
	// 										'default_value' => '',
	// 										'placeholder' => '',
	// 										'prepend' => '',
	// 										'append' => '',
	// 										'formatting' => 'html',
	// 										'maxlength' => '',
	// 									),
	// 								),
	// 								'row_min' => '',
	// 								'row_limit' => '',
	// 								'layout' => 'table',
	// 								'button_label' => 'Add Row',
	// 							),
	// 							array (
	// 								'key' => 'field_5c150b7eef146',
	// 								'label' => 'See More Text',
	// 								'name' => 'see_more_text',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 							array (
	// 								'key' => 'field_5c150b8bef147',
	// 								'label' => 'See More Link',
	// 								'name' => 'see_more_link',
	// 								'type' => 'text',
	// 								'column_width' => '',
	// 								'default_value' => '',
	// 								'placeholder' => '',
	// 								'prepend' => '',
	// 								'append' => '',
	// 								'formatting' => 'html',
	// 								'maxlength' => '',
	// 							),
	// 						),
	// 					),
	// 				),
	// 				'button_label' => 'Add Row',
	// 				'min' => '',
	// 				'max' => '',
	// 			),
	// 		),
	// 		'location' => array (
	// 			array (
	// 				array (
	// 					'param' => 'page',
	// 					'operator' => '==',
	// 					'value' => '567',
	// 					'order_no' => 0,
	// 					'group_no' => 0,
	// 				),
	// 			),
	// 		),
	// 		'options' => array (
	// 			'position' => 'normal',
	// 			'layout' => 'no_box',
	// 			'hide_on_screen' => array (
	// 				0 => 'the_content',
	// 				1 => 'featured_image',
	// 			),
	// 		),
	// 		'menu_order' => 0,
	// 	));
	// 	register_field_group(array (
	// 		'id' => 'acf_site',
	// 		'title' => 'Site',
	// 		'fields' => array (
	// 			array (
	// 				'key' => 'field_5a9b107a8a363',
	// 				'label' => 'Logo',
	// 				'name' => 'logo',
	// 				'type' => 'image',
	// 				'save_format' => 'object',
	// 				'preview_size' => 'thumbnail',
	// 				'library' => 'all',
	// 			),
	// 			array (
	// 				'key' => 'field_5aa39be30ae18',
	// 				'label' => 'Newsletter Heading',
	// 				'name' => 'newsletter_heading',
	// 				'type' => 'wysiwyg',
	// 				'default_value' => '',
	// 				'toolbar' => 'full',
	// 				'media_upload' => 'no',
	// 			),
	// 			array (
	// 				'key' => 'field_5aa39446737e1',
	// 				'label' => 'Newsletter Form',
	// 				'name' => 'newsletter_form',
	// 				'type' => 'acf_cf7',
	// 				'disable' => array (
	// 					0 => 0,
	// 				),
	// 				'allow_null' => 0,
	// 				'multiple' => 0,
	// 				'hide_disabled' => 0,
	// 			),
	// 			array (
	// 				'key' => 'field_5aa3a00c6267a',
	// 				'label' => 'Social Accounts',
	// 				'name' => 'social_accounts',
	// 				'type' => 'repeater',
	// 				'sub_fields' => array (
	// 					array (
	// 						'key' => 'field_5aa3a01b6267b',
	// 						'label' => 'Site Name',
	// 						'name' => 'social_site_name',
	// 						'type' => 'text',
	// 						'column_width' => '',
	// 						'default_value' => '',
	// 						'placeholder' => '',
	// 						'prepend' => '',
	// 						'append' => '',
	// 						'formatting' => 'html',
	// 						'maxlength' => '',
	// 					),
	// 					array (
	// 						'key' => 'field_5aa3a0b46267c',
	// 						'label' => 'URL',
	// 						'name' => 'social_site_url',
	// 						'type' => 'text',
	// 						'column_width' => '',
	// 						'default_value' => '',
	// 						'placeholder' => '',
	// 						'prepend' => '',
	// 						'append' => '',
	// 						'formatting' => 'html',
	// 						'maxlength' => '',
	// 					),
	// 				),
	// 				'row_min' => '',
	// 				'row_limit' => '',
	// 				'layout' => 'table',
	// 				'button_label' => 'Add Row',
	// 			),
	// 			array (
	// 				'key' => 'field_5aa5b47aab1ec',
	// 				'label' => 'Footer CTA content (left)',
	// 				'name' => 'footer_cta_content_left',
	// 				'type' => 'wysiwyg',
	// 				'default_value' => '',
	// 				'toolbar' => 'full',
	// 				'media_upload' => 'yes',
	// 			),
	// 			array (
	// 				'key' => 'field_5aa5b565958d5',
	// 				'label' => 'Footer CTA content (right)',
	// 				'name' => 'footer_cta_content_right',
	// 				'type' => 'wysiwyg',
	// 				'default_value' => '',
	// 				'toolbar' => 'full',
	// 				'media_upload' => 'yes',
	// 			),
	// 			array (
	// 				'key' => 'field_5aa3a3958748b',
	// 				'label' => 'Footer Text',
	// 				'name' => 'footer_text',
	// 				'type' => 'wysiwyg',
	// 				'default_value' => '',
	// 				'toolbar' => 'full',
	// 				'media_upload' => 'no',
	// 			),
	// 			array (
	// 				'key' => 'field_5bbbb592a5574',
	// 				'label' => 'Contact Modal',
	// 				'name' => 'contact_modal',
	// 				'type' => 'acf_cf7',
	// 				'disable' => array (
	// 					0 => 0,
	// 				),
	// 				'allow_null' => 0,
	// 				'multiple' => 0,
	// 				'hide_disabled' => 0,
	// 			),
	// 		),
	// 		'location' => array (
	// 			array (
	// 				array (
	// 					'param' => 'options_page',
	// 					'operator' => '==',
	// 					'value' => 'acf-options',
	// 					'order_no' => 0,
	// 					'group_no' => 0,
	// 				),
	// 			),
	// 		),
	// 		'options' => array (
	// 			'position' => 'normal',
	// 			'layout' => 'no_box',
	// 			'hide_on_screen' => array (
	// 				0 => 'the_content',
	// 			),
	// 		),
	// 		'menu_order' => 0,
	// 	));
	// }


?>